spring:
  profiles:
    active: local
  application:
    name: chefia
  datasource:
    url: jdbc:postgresql://chefia_db:5432/chefia
    username: chefia
    password: chefia123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  sql:
    init:
      continue-on-error: true

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        jdbc:
          datasource: DEBUG

springdoc:
  swagger-ui:
    url: /api/users.yaml

api:
  security:
    token:
      secret: ${JWT_SECRET:carlosEduardoRinconJunior}
