openapi: 3.0.3
info:
  title: User Types API
  version: 1.0.0
  description: API for managing user types
  contact:
    name: Carlos Eduardo Rincon Junior
    email: carlos.rincon.junior@aluno.ifsp.edu.br
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080/
    description: Local server
tags:
  - name: UserTypes
    description: Operations related to user types
paths:
  /usertype:
    get:
      tags:
        - UserTypes
      summary: List all user types
      operationId: listUserTypes
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
            example: 1
        - name: perPage
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        "200":
          description: A list of user types
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedUserType"
    post:
      tags:
        - UserTypes
      summary: Create a new user type
      operationId: createUserType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserType"
      responses:
        "201":
          description: User type created
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: /user/123e4567-e89b-12d3-a456-426614174000
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserType"
  /usertype/{userTypeId}:
    get:
      tags:
        - UserTypes
      summary: Get a user type by ID
      operationId: getUserType
      parameters:
        - name: userTypeId
          in: path
          description: ID of the user type to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: User Type found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserType"
        "400":
          description: Bad request
        "404":
          description: User type not found
    put:
      tags:
        - UserTypes
      summary: Update a user type
      operationId: updateUserType
      parameters:
        - name: userTypeId
          in: path
          description: ID of the user type to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserType"
      responses:
        "200":
          description: User type updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserType"
        "404":
          description: User type not found
    delete:
      tags:
        - UserType
      summary: Delete a user type
      operationId: deleteUserType
      parameters:
        - name: userTypeId
          in: path
          description: ID of the user type to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: User type deleted
        "400":
          description: Bad request
components:
  schemas:
    CreateUserType:
      required:
        - name
        - description
      type: object
      properties:
        name:
          type: string
          description: Name of the user type
          minLength: 5
          maxLength: 100
          example: Admin
        description:
          type: string
          description: Description of the user type
          minLength: 5
          maxLength: 100
          example: User type to manage other users
    UpdateUserType:
      type: object
      properties:
        name:
          type: string
          description: Name of the user type
          minLength: 5
          maxLength: 100
          example: Admin
        description:
          type: string
          description: Description of the user type
          minLength: 5
          maxLength: 100
          example: User type to manage other users
        active:
          type: boolean
          description: Flag to active or disable user type
          example: true
    PaginatedUserType:
      type: object
      properties:
        page:
          type: integer
          example: 1
        perPage:
          type: integer
          example: 10
        total:
          type: integer
          format: int64
          example: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/UserType"
    UserType:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Id of the user type
          maxLength: 10
          example: 15
        name:
          type: string
          description: Name of the user
          maxLength: 100
          example: Carlos
        description:
          type: string
          description: Description of the user type
          minLength: 5
          maxLength: 100
          example: User type to manage other users
        active:
          type: boolean
          description: Flag to active or disable user type
          example: true
        createdAt:
          type: string
          format: date-time
          description: Date and time when the user was created
          example: 2025-07-17T21:00:00
        updatedAt:
          type: string
          format: date-time
          description: Date and time when the user was updated
          example: 2025-07-17T21:00:00